FROM  python


RUN apt-get update \
     && apt-get install -y --no-install-recommends gnupg


# Adding Google chrome headless
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

RUN apt-get -y update \
   && apt-get install -y google-chrome-stable

RUN wget -O /tmp/chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip && unzip /tmp/chromedriver.zip && cp chromedriver-linux64/chromedriver /usr/local/bin/
